### PR TITLE
EVA-189 Only Spring Batch dynamic workflow to skip steps

### PR DESCRIPTION
**Pull request by cyenyxe**
Even after introducing dynamic workflows, some steps were still using manual checks, so half the "step skipping" capabilities were based on DW and others in those checks. This is no longer the case, and only full statistics and annotation flows are skippable using the dynamic workflow.

The `VariantLoadConfiguration` class has been removed since it is not something that only makes sense inside the `VariantConfiguration` workflow. Related tests have been integrated into the `VariantConfigurationTest` class.

Finally, those places were free text strings were still being used to name steps or flows have been replaced by constants.

### CODE REVIEW

**Comment by jmmut** [comment]
if all the strings for steps, jobs or flows are to be replaced, the new class `GenesLoad` needs to be updated, and the tests have these:
```
jmmut@tesla:~/appl/eva-pipeline/src[cyenyxe-dynamic-workflow']$ grep -rn "\.launch[^\.].*\""
test/java/embl/ebi/variation/eva/pipeline/steps/VariantsAnnotGenerateInputTest.java:111:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Find variants to annotate");
test/java/embl/ebi/variation/eva/pipeline/steps/VariantsAnnotLoadTest.java:96:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Load VEP annotation");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantStatsConfigurationTest.java:112:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Calculate statistics");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantStatsConfigurationTest.java:156:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Calculate statistics");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantStatsConfigurationTest.java:176:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Load statistics");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantStatsConfigurationTest.java:231:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Load statistics");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationTest.java:120:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Normalize variants");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationTest.java:153:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Normalize variants");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationTest.java:181:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Load variants");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationTest.java:218:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Load variants");
test/java/embl/ebi/variation/eva/pipeline/jobs/VariantAnnotConfigurationTest.java:135:        JobExecution jobExecution = jobLauncherTestUtils.launchStep("Generate VEP annotation");
```

**Comment by cyenyxe** [comment]
Changes made to `GenesLoad` and test classes.

**Comment by jmmut** [comment]
I just saw this https://github.com/cyenyxe/eva-pipeline/blob/59497564ec2c28ec24334ef84844a0a350f1b305/src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantAggregatedConfigurationTest.java#L170 and this https://github.com/cyenyxe/eva-pipeline/blob/59497564ec2c28ec24334ef84844a0a350f1b305/src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantAggregatedConfigurationTest.java#L248. Silly things, but I guess this is a good PR to do it.

**Comment by jmmut** [comment]
more strings replacements https://github.com/cyenyxe/eva-pipeline/blob/59497564ec2c28ec24334ef84844a0a350f1b305/src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantAnnotConfigurationTest.java#L113  and https://github.com/cyenyxe/eva-pipeline/blob/59497564ec2c28ec24334ef84844a0a350f1b305/src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationTest.java#L335

**Pull request merged**
